"""baseline after app refactor

Revision ID: 11b3d3a40fd8
Revises: 
Create Date: 2025-06-12 18:52:24.681172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b3d3a40fd8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'trades',
        sa.Column('id', sa.VARCHAR(), primary_key=True, nullable=False),
        sa.Column('ticker', sa.VARCHAR(), nullable=False),
        sa.Column('strategy', sa.VARCHAR(), nullable=False),
        sa.Column('strike', sa.FLOAT(), nullable=False),
        sa.Column('expiry', sa.DATE(), nullable=False),
        sa.Column('entry_price', sa.FLOAT(), nullable=True),
        sa.Column('premium', sa.FLOAT(), nullable=False),
        sa.Column('delta', sa.FLOAT(), nullable=False),
        sa.Column('annualized_yield', sa.FLOAT(), nullable=False),
        sa.Column('pop', sa.FLOAT(), nullable=False),
        sa.Column('status', sa.VARCHAR(length=15), nullable=True),
        sa.Column('execution_source', sa.VARCHAR(length=12), nullable=True),
        sa.Column('live_trading_enabled', sa.BOOLEAN(), nullable=True),
        sa.Column('result', sa.FLOAT(), nullable=True),
        sa.Column('rationale', sa.VARCHAR(), nullable=True),
        sa.Column('created_at', sa.DATE(), nullable=False),
        sa.Column('updated_at', sa.DATE(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    # ### end Alembic commands ###
